add Assignment 4: Design Patterns
MeloDuarte/faast pull request #7
Opened 2023-06-13 22:23 UTC by MeloDuarte

2023-06-20 09:24 UTC, dgenio commented
@MeloDuarte can you improve PR description to explain what was your goal, what you did and why?

2023-06-20 09:47 UTC, dgenio commented on life_expectancy/cleaning.py
> +def main(country: Region=Region.PT, loader: str='tsv') -> None:
Maybe rename loader with load_file_type

2023-06-20 09:47 UTC, dgenio commented on life_expectancy/cleaning.py
> +def main(country: Region=Region.PT, loader: str='tsv') -> None:
You lose the ability to define other files to be treated bt main, was this intencional?

2023-06-20 09:47 UTC, dgenio commented on life_expectancy/strategies.py
> +        return countries
Normalize use of country/region in the class
```suggestion
    def get_countries(cls) -> List[str]:
        """
        Filters valid countries.
        :return: A list of region codes representing valid countries.
        """
        not_countries = [
            'EU27_2020',
            'DE_TOT',
            'EA18',
            'EA19',
            'EFTA',
            'EEA30_2007',
            'EEA31',
            'EU27_2007',
            'EU28'
        ]
        countries = [region.value for region in cls if region.value not in not_countries]
        return countries
```

2023-06-20 09:47 UTC, dgenio commented on life_expectancy/strategies.py
> +class LoadDataStrategy(ABC):
This is more that Load - is a Load&CleanDataStrategy

I suggest that you either rename or split this into two

2023-06-20 09:47 UTC, dgenio commented on life_expectancy/strategies.py
> +        return expectancy_result
This function as at least 3 different responsibilities:

1. unpivot data
2. ensure some columns quality ( year and value)
3. filter by region

Do you think it makes sense to split it into 3 private functions?

2023-06-20 09:47 UTC, dgenio commented on life_expectancy/tests/test_cleaning.py
There's not test for LoadJSONDataStrategy ?

2023-06-20 15:04 UTC, MeloDuarte commented on life_expectancy/cleaning.py
> +def main(country: Region=Region.PT, loader: str='tsv') -> None:
Yes, taking into account that the cleaning is not generalizable...potentially we will have to create a different cleaning/load classes and condition for each specific file type..

2023-06-20 15:19 UTC, MeloDuarte commented on life_expectancy/strategies.py
> +class LoadDataStrategy(ABC):
I understand your point but incorporating some cleaning or pre-processing in this context (simple filtering) within the load class can ensure a coherent representation without implying a complex class structure. Maybe in a more complex cleaning, with data fusion or a similar task I would be more inclined to consider your suggestion.

2023-06-20 15:41 UTC, MeloDuarte commented on life_expectancy/tests/test_cleaning.py
done

2023-06-20 16:04 UTC, MeloDuarte commented on life_expectancy/strategies.py
> +        return expectancy_result
done

2023-06-20 16:28 UTC, MrCordeiro requested changes
You're testing like a pro now!

2023-06-20 16:28 UTC, MrCordeiro commented on life_expectancy/cleaning.py
> +    parser.add_argument("-country", default=Region.PT, help="Filters data by `country`")
This "country" argument will be in the format of a str. Only the default will be as a Region.
In order to transform it into an Enum, you should pass `Region(args.country)` to your main. 

This has the extra benefit of running the Enum validation to the input.

(you could also try adding the option `type=Region` to the add_argument call. I'm not sure, but it would make sense if that converts the user input directly into an Region... it's the same process as parsing a datetime)

2023-06-20 16:28 UTC, MrCordeiro commented on life_expectancy/strategies.py
> +class LoadDataStrategy(ABC):
I tend to agree with @dgenio... Were this class to be named `DataStrategy` I would agree with you. But because it was called `LoadData` I was surprised to see a cleaning method inside.

I think it's fine to have both loading and cleaning in the same class... but that intent has to be conveyed in its name.

2023-06-20 16:28 UTC, MrCordeiro commented on life_expectancy/strategies.py
> +    def _ensure_column_quality(expectancy_region: DataFrame) -> DataFrame:
As you extract functions, you reduce the coupling in your code. This is nice!

Now this function could potentially work on all dataframes and not only filtered one. It provides a good opportunity to rename all dataframe inputs with the same name.

At this point, you'll notice that they all share the same arguments: so you can now transform that argument into a class instance variable! And, with that, you will e making full use of your class!

2023-06-20 16:28 UTC, MrCordeiro commented on life_expectancy/strategies.py
> +    print(filename)
Is this print a leftover from a debugging session? Perhaps a log would be more appropriate... or maybe just deleting it.

2023-06-25 18:32 UTC, dgenio approved these changes

2023-06-26 09:26 UTC, merged